name: Docs

on:
  push:
    branches: [master]

jobs:
  deploy_doc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

<<<<<<< HEAD
      - run: mdbook build
=======
      - run: mdbook build docs
>>>>>>> c38889c... feat: add mdbook

      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.DEPLOY_KEY}}
<<<<<<< HEAD
          publish_dir: ./book
=======
          publish_dir: ./docs/book
>>>>>>> c38889c... feat: add mdbook
