name: Docs

on:
  pull_request:
    branches: [master]

jobs:
  build_doc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

<<<<<<< HEAD
      - run: mdbook build
=======
      - run: mdbook build docs
>>>>>>> c38889c... feat: add mdbook
